### ISSUE TITLE
Need a tissue for these issues

### ISSUE THREAD

**Issue by vchi90** [emai1/Pineapple-Pizza#2]
statement of problem
    Pass ✓
    Only possible issue is that Holmes advised against the usage of a 'starting position' within the statement of the problem, but it seems to work without 'leave', based on today's (4/10) class.

recursive abstraction
    Pass ✓
    Note that "go" in your pseudocode can also refer to "moving one position". Can fix up but the message should be clear regardless.

base cases
    Great Stuff ✓

English or pseudocode description of algorithm
    Great Stuff ✓

**Comment by emai1** [comment]
Thanks for the feedback, will relook the wording. ✓
